// Auto-generated by tools/mkcard.py. Do not edit: re-run it.
//
// What the card file holds and in what order, for a build with CARDIMAGES on. The layout
// is set out in tools/mkcard.py; this only names the entries so the game can ask for one
// by name and check that the card it found was made by this build.

#pragma once
#include <stdint.h>

//the file the game looks for in the card's root
#define CARD_FILE_NAME "PUZZLELA.DAT"

//the same name as a FAT directory entry holds it: eight characters then three, no dot,
//which is the form CHSd's fat::find takes
#define CARD_FILE_83 "PUZZLELADAT"

//every skin and picture name, hashed: a card made by another build has another stamp
#define CARD_STAMP 0x724C97E9UL

//the sections of the container, by the name its table holds. Levels will be another one
#define CARD_SEC_IMAGES "IMGS"
#define CARD_SEC_LEVELS "LVLS"

//1 when any picture is kept as one colour a row, see FMT_ROWS. The game builds the
//code that draws one only then: a card without any is a game that need not carry it
#define CARD_HAS_ROWS 0

#define CARD_SKIN_COUNT 2
#define CARD_IMAGE_COUNT 38

//the skins, in the order the index holds them
enum CardSkin : uint8_t
{
	CARD_SKIN_DEFAULT = 0,
	CARD_SKIN_BLACK_WHITE = 1,
};

//what each skin is called on screen
#define CARD_SKIN_NAMES { "Default", "Black & white" }

//the pictures, in the order the index holds them within a skin
enum CardImage : uint8_t
{
	CARD_IMG_BETWEENSTAGE = 0,
	CARD_IMG_BETWEENSTAGELEVEL1 = 1,
	CARD_IMG_BLOCKACTIVEIMAGE = 2,
	CARD_IMG_BLOCKIMAGE = 3,
	CARD_IMG_BORDER1 = 4,
	CARD_IMG_BORDER2 = 5,
	CARD_IMG_BORDER3 = 6,
	CARD_IMG_BORDER4 = 7,
	CARD_IMG_BORDER5 = 8,
	CARD_IMG_BORDER6 = 9,
	CARD_IMG_BORDER7 = 10,
	CARD_IMG_BRIDGE = 11,
	CARD_IMG_HAND = 12,
	CARD_IMG_INTRO = 13,
	CARD_IMG_OLDMAN = 14,
	CARD_IMG_OPTIONSSELECT = 15,
	CARD_IMG_PAPER = 16,
	CARD_IMG_ROOMBACKGROUND = 17,
	CARD_IMG_RYF_CLOUD = 18,
	CARD_IMG_RYF_FAIRY = 19,
	CARD_IMG_RYF_PLAYER = 20,
	CARD_IMG_RYF_SHADOW = 21,
	CARD_IMG_RYF_SMALLCLOUD = 22,
	CARD_IMG_SELECT = 23,
	CARD_IMG_SPACESHIP = 24,
	CARD_IMG_STAGEBLOCK1 = 25,
	CARD_IMG_STAGEBLOCK10 = 26,
	CARD_IMG_STAGEBLOCK2 = 27,
	CARD_IMG_STAGEBLOCK3 = 28,
	CARD_IMG_STAGEBLOCK4 = 29,
	CARD_IMG_STAGEBLOCK5 = 30,
	CARD_IMG_STAGEBLOCK6 = 31,
	CARD_IMG_STAGEBLOCK7 = 32,
	CARD_IMG_STAGEBLOCK8 = 33,
	CARD_IMG_STAGEBLOCK9 = 34,
	CARD_IMG_STAGECLEARKADER = 35,
	CARD_IMG_TITLE = 36,
	CARD_IMG_TITLESELECTOR = 37,
};

//1 when the card holds the level packs too, so the game reads them from there and not
//out of flash. 0 leaves everything about the levels as it was
#define CARD_HAS_LEVELS 1

#define CARD_LEVEL_COUNT 36

//the packs, in the order the index holds them, by the name the game knows
#define CARD_LEVEL_NAMES { "puzzleland/level1.lev", "puzzleland/level2.lev", "puzzleland/level3.lev", "puzzleland/level4.lev", "puzzleland/level5.lev", "puzzleland/level6.lev", "puzzleland/level7.lev", "puzzleland/level8.lev", "puzzleland/level9.lev", "puzzleland/level10.lev", "puzzleland/level11.lev", "puzzleland/level12.lev", "puzzleland/level13.lev", "puzzleland/level14.lev", "puzzleland/level15.lev", "puzzleland/level16.lev", "puzzleland/level17.lev", "puzzleland/level18.lev", "puzzleland/level19.lev", "puzzleland/level20.lev", "puzzleland/level21.lev", "puzzleland/level22.lev", "puzzleland/level23.lev", "puzzleland/level24.lev", "puzzleland/level25.lev", "puzzleland/level26.lev", "puzzleland/level27.lev", "puzzleland/level28.lev", "puzzleland/level29.lev", "puzzleland/level30.lev", "puzzleland/level31.lev", "puzzleland/level32.lev", "puzzleland/level33.lev", "puzzleland/level34.lev", "puzzleland/level35.lev", "puzzleland/level36.lev" }

//how many levels each pack holds, the entries above being one flat list
#define CARD_LEVEL_PACKS 1
#define CARD_LEVEL_PACK_COUNTS { 36 }
