// Auto-generated by tools/mkcard.py. Do not edit: re-run it.
//
// What the card file holds and in what order, for a build with CARDIMAGES on. The layout
// is set out in tools/mkcard.py; this only names the entries so the game can ask for one
// by name and check that the card it found was made by this build.

#pragma once
#include <stdint.h>

//the file the game looks for in the card's root
#define CARD_FILE_NAME "PUZZLELA.DAT"

//the same name as a FAT directory entry holds it: eight characters then three, no dot,
//which is the form CHSd's fat::find takes
#define CARD_FILE_83 "PUZZLELADAT"

//every skin and picture name, hashed: a card made by another build has another stamp
#define CARD_STAMP 0xECA4B8F6UL

//the sections of the container, by the name its table holds. Levels will be another one
#define CARD_SEC_IMAGES "IMGS"

//1 when any picture is kept as one colour a row, see FMT_ROWS. The game builds the
//code that draws one only then: a card without any is a game that need not carry it
#define CARD_HAS_ROWS 0

#define CARD_SKIN_COUNT 2
#define CARD_IMAGE_COUNT 38

//the skins, in the order the index holds them
enum CardSkin : uint8_t
{
	CARD_SKIN_DEFAULT = 0,
	CARD_SKIN_BLACK_WHITE = 1,
};

//what each skin is called on screen
#define CARD_SKIN_NAMES { "Default", "Black & white" }

//the pictures, in the order the index holds them within a skin
enum CardImage : uint8_t
{
	CARD_IMG_BETWEENSTAGE = 0,
	CARD_IMG_BETWEENSTAGELEVEL1 = 1,
	CARD_IMG_BLOCKACTIVEIMAGE = 2,
	CARD_IMG_BLOCKIMAGE = 3,
	CARD_IMG_BORDER1 = 4,
	CARD_IMG_BORDER2 = 5,
	CARD_IMG_BORDER3 = 6,
	CARD_IMG_BORDER4 = 7,
	CARD_IMG_BORDER5 = 8,
	CARD_IMG_BORDER6 = 9,
	CARD_IMG_BORDER7 = 10,
	CARD_IMG_BRIDGE = 11,
	CARD_IMG_HAND = 12,
	CARD_IMG_INTRO = 13,
	CARD_IMG_OLDMAN = 14,
	CARD_IMG_OPTIONSSELECT = 15,
	CARD_IMG_PAPER = 16,
	CARD_IMG_ROOMBACKGROUND = 17,
	CARD_IMG_RYF_CLOUD = 18,
	CARD_IMG_RYF_FAIRY = 19,
	CARD_IMG_RYF_PLAYER = 20,
	CARD_IMG_RYF_SHADOW = 21,
	CARD_IMG_RYF_SMALLCLOUD = 22,
	CARD_IMG_SELECT = 23,
	CARD_IMG_SPACESHIP = 24,
	CARD_IMG_STAGEBLOCK1 = 25,
	CARD_IMG_STAGEBLOCK10 = 26,
	CARD_IMG_STAGEBLOCK2 = 27,
	CARD_IMG_STAGEBLOCK3 = 28,
	CARD_IMG_STAGEBLOCK4 = 29,
	CARD_IMG_STAGEBLOCK5 = 30,
	CARD_IMG_STAGEBLOCK6 = 31,
	CARD_IMG_STAGEBLOCK7 = 32,
	CARD_IMG_STAGEBLOCK8 = 33,
	CARD_IMG_STAGEBLOCK9 = 34,
	CARD_IMG_STAGECLEARKADER = 35,
	CARD_IMG_TITLE = 36,
	CARD_IMG_TITLESELECTOR = 37,
};
